// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors
#pragma once

#include "Nodes/FlowNode.h"
#include "FlowNode_SubGraph_Interface.h"

#include "FlowNode_AbstractSubGraph.generated.h"

class UFlowAssetParams;

/**
 * Creates instance of provided Flow Asset and starts its execution.
 */
UCLASS(Abstract, NotBlueprintable)
class FLOW_API UFlowNode_AbstractSubGraph : public UFlowNode,
                                            public IFlowNodeSubGraphInterface
{
	GENERATED_UCLASS_BODY()

public:
	friend class UFlowAsset;
	friend class FFlowNode_SubGraphDetails;
	friend class UFlowSubsystem;

	static FFlowPin StartPin;
	static FFlowPin FinishPin;

private:
	/* Flow Asset Params to use as the data pin value supplier for the Asset. */
	UPROPERTY(EditAnywhere, Category = "Graph", meta = (DefaultForInputFlowPin, FlowPinType = "Object"))
	TSoftObjectPtr<UFlowAssetParams> AssetParams;

	/* Allow to create instance of the same Flow Asset as the asset containing this node.
	 * Enabling it may cause an infinite loop, if graph would keep creating copies of itself. */
	UPROPERTY(EditAnywhere, Category = "Graph")
	bool bCanInstanceIdenticalAsset;

	UPROPERTY(SaveGame)
	FString SavedAssetInstanceName;

	UPROPERTY(SaveGame)
	FFlowParameter CachedFlowParameter;

public:
	virtual UFlowNode* GetOwningFlowNode() const override;
	virtual UFlowAsset* GetOwningFlowAsset() const override;
	virtual TSoftObjectPtr<UFlowAsset> GetSubFlowAsset() const override;
	virtual TScriptInterface<IFlowDataPinValueSupplierInterface> GetFlowDataPinValueSupplierInterface() const override;

	virtual void OnFinishOutput(const FFlowParameter& FlowParameter) override;
	virtual void OnFlowAssetSave(const FFlowAssetSaveData& SubAssetRecord) override;

protected:
	virtual bool CanBeAssetInstanced() const;

	virtual void PreloadContent() override;
	virtual void FlushContent() override;

	virtual void ExecuteInput(const FName& PinName, const FFlowParameter& FlowParameter) override;
	virtual void ExecuteSubGraphStartInput(const FName& Name, const FFlowParameter& FlowParameter);
	virtual void ExecuteSubGraphCustomInput(const FName& Name, const FFlowParameter& FlowParameter);
	virtual void Cleanup() override;

	virtual void CreateSubFlow(const FString SavedInstanceName, const bool bPreloading = false,
	                           const FFlowParameter& FlowParameter = FFlowParameter());

	// Call the Default Start Node Entry Input
	virtual void TriggerEntryInput(const FFlowParameter& FlowParameter = FFlowParameter());
	virtual void TriggerCustomInput(const FName& EventName, const FFlowParameter& FlowParameter = FFlowParameter());

protected:
	virtual TSoftObjectPtr<UFlowAsset> GetSubAsset() const;

public:
	virtual void ForceFinishNode() override;

protected:
	virtual void OnLoad_Implementation() override;

#if WITH_EDITORONLY_DATA

protected:
	/* All the classes allowed to be used as assets on this subgraph node. */
	UPROPERTY()
	TArray<TSubclassOf<UFlowAsset>> AllowedAssignedAssetClasses;

	/* All the classes disallowed to be used as assets on this subgraph node. */
	UPROPERTY()
	TArray<TSubclassOf<UFlowAsset>> DeniedAssignedAssetClasses;
#endif

#if WITH_EDITOR

public:
	virtual FText K2_GetNodeTitle_Implementation() const override;
	virtual FString GetNodeDescription() const override;
	virtual UObject* GetAssetToEdit() override;
	virtual EDataValidationResult ValidateNode() override;

	// IFlowContextPinSupplierInterface
	virtual bool SupportsContextPins() const override { return true; }
	virtual TArray<FFlowPin> GetContextInputs() const override;
	virtual TArray<FFlowPin> GetContextOutputs() const override;
	// --

	virtual void AutoGenerateDataPins(FFlowAutoDataPinsWorkingData& InOutWorkingData) const override;

	// IFlowDataPinValueSupplierInterface
	virtual FFlowDataPinResult TrySupplyDataPin(FName PinName) const override;
	// --

	// UObject
	virtual void PostLoad() override;
	// --

protected:
	void SubscribeToAssetChanges();
	void UnsubscribeToAssetChanges();
#endif

	static const FName AssetParams_MemberName;
};
